### PR TITLE
Create a partial symlink tree of the NDK rather than symlinking just …

### LINKED ISSUE #3: Don't create BUILD files in the NDK installation directory
For simplicity, the top-level `toolchains` directory of the NDK is symlinked into the external repository directory, but this means that when `android_ndk_repository` creates BUILD files, they're created in the real NDK installation directory: 

https://github.com/bazelbuild/rules_android_ndk/blob/631ba9afc76862ed3aa715ec292c03ed2724a3e0/rules.bzl#L61

https://github.com/bazelbuild/rules_android_ndk/blob/631ba9afc76862ed3aa715ec292c03ed2724a3e0/rules.bzl#L76

### PR DESCRIPTION
**Pull request by ahumesky**
…the `toolchains` directory, to avoid creating BUILD files in the real NDK directories. Fixes #3.

### CODE REVIEW

**Review by ted-xie — APPROVED** [review]

**Comment by keith** [comment]
Assuming the CI update has been pushed on the bazel side the failure here is because it's still looking at the old NDK dir, but I can probably look at that separately if you want

**Comment by ahumesky** [comment]
sounds like we won't be able to get this to pass on mac for a bit (https://github.com/bazelbuild/continuous-integration/pull/1434#issuecomment-1245581562) but it would be good to get this to pass at least on linux on CI before merging, so please feel free!

**Comment by keith** [comment]
you can merge this one if it's good locally i'd say and I can work on another PR

**Comment by ahumesky** [comment]
I set this up: https://github.com/bazelbuild/rules_android_ndk/pull/15 so perhaps that's enough to get at least linux working

**Comment by ahumesky** [comment]
Looks like NDK 25b is set up and it's getting picked up, but now the test is failing like this:
https://buildkite.com/bazel/rules-android-ndk/builds/9#01833901-70f1-44a2-b9ee-8d5ad5c57119/222-245

I believe that's because the ci is set up to test `//...` in the example directory, which would pick up the `cc_library` as a top-level target, which means it's also getting built in the top-level configuration which doesn't have the android configuration set up by the transition in `android_binary`. I'll just list the target specifically for now

**Comment by ahumesky** [comment]
This managed to pass on linux:
https://buildkite.com/bazel/rules-android-ndk/builds/10#01833910-40d4-4aa7-b1e6-18a9a459e03c/222-235

so that will have to be good enough for now

**Pull request merged**
