### PR TITLE
Set ANDROID_NDK_HOME for mac

### PR DESCRIPTION
**Pull request by meteorcloudy**

### CODE REVIEW

**Comment by meteorcloudy** [comment]
The macOS build also pass now, https://buildkite.com/bazel/rules-android-ndk/builds/13#01833bb7-97d4-43fe-9a68-1ec690d0156b

**Comment by meteorcloudy** [comment]
You probably want to fix the buildifier error so that the pipeline is green

**Comment by keith** [comment]
buildifier fix https://github.com/bazelbuild/rules_android_ndk/pull/18

so i'd say we should just merge this one, thanks for doing it!

**Comment by ahumesky** [comment]
> You probably want to fix the buildifier error so that the pipeline is green, then we can enable it in downstream pipeline so you also get test coverage from Bazel@HEAD

hmm I had run buildifier yesterday:
https://github.com/bazelbuild/rules_android_ndk/commit/5c8acc87b851179380ed5713acfd4a10430d42f5

buildifier on buildkite doesn't say what's wrong within the files so not sure why it's still giving errors

**Review by ahumesky — APPROVED** [review]

**Pull request merged**
