### PR TITLE
Make rules_android_ndk compatible with bzlmod without needing a WORSPACE file

### PR DESCRIPTION
**Pull request by ahumesky**
Also updates the example use the Starlark Android rules.

### CODE REVIEW

**Review by ted-xie — CHANGES_REQUESTED** [review]
Let's also add an empty WORKSPACE.bzlmod, since otherwise the WORKSPACE file will get pulled in.

**Comment by Attempt3035** [comment]
This is exactly what I've been looking for! Keen to see this merged 🙌

**Comment by ahumesky** [comment]
> Let's also add an empty WORKSPACE.bzlmod, since otherwise the WORKSPACE file will get pulled in.

Good point, I added one to the root as well as to the example root

**Review by ted-xie — APPROVED** [review]

**Review by Wyverald — APPROVED** [review]
nice!

**Comment by ahumesky** [comment]
Hmm of course I can't locally reproduce the `external\org_golang_google_protobuf\reflect\protoreflect\value_union.go:70:12: undefined: value` error happening with go protobufs on windows on BazelCI...

**Comment by ahumesky** [comment]
We don't test non-bzlmod on windows with rules_android either, and that's broken in the same way:
https://buildkite.com/bazel/rules-android/builds/2776#019075fb-acdf-4456-a39c-677cdfe9d154

So to unblock this PR, I'm just going to remove the non-bzlmod tests for this on windows

**Comment by ahumesky** [comment]
After some investigation (i.e. toil) it looks like this came down to the "value_pure.go" file being left out of a build file generated by gazelle for org_golang_google_protobuf, which I guess might have been a bug in gazelle because updating to the latest version in rules_android seems to have fixed it

**Comment by ahumesky** [comment]
I'm pretty sure the buildifier changes to the workspace file where it rearranges the load statements to the top will break things, so I'm just going to ignore it.

**Comment by Attempt3035** [comment]
Got this up and working on my setup, love it thanks so much for the great work @ahumesky !!

**Pull request merged**
